#ifndef MANIADANOVERLAY_IDENTITY_H
#define MANIADANOVERLAY_IDENTITY_H

#define MANIADANOVERLAY_NAME "ManiaDanOverlay"
#define MANIADANOVERLAY_AUTHOR "Tanese"
#define MANIADANOVERLAY_TITLE "ManiaDanOverlay by Tanese"

#ifndef MANIADANOVERLAY_VERSION
#define MANIADANOVERLAY_VERSION "1.0.0"
#endif

#define MANIADANOVERLAY_USER_AGENT \
    "ManiaDanOverlay/" MANIADANOVERLAY_VERSION

#endif
